### ISSUE TITLE
User story #11  - Who publish? 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#11]
As a comms person I want to know who published to 360giving so I can create a story about it.

**Comment by stevieflow** [comment]
It may be semantics, but I would advise we think again about the phrase:

> who published to 360giving

People don't - technically - publish *to* 360Giving.  It is not a reporting mechanism.  "Publish to" can imply that.  

Conversely, the 360 Registry is centrally administered.  Therefore, the list the registry makes available is curated - as others publishing 360 data may exist, but not yet (for a variety of reasons) be "registered"

Therefore, I think this story could be represented as:

As a comms person I want to know who has published data using the 360Giving standard, so that I can create a story about it
