### ISSUE TITLE
Decide placement and content of signposting text from Data Registry

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/registry#122]
The current Data Registry includes simple text and signposting to other resources at the top of the list

![image](https://user-images.githubusercontent.com/20462640/182834767-6ad2bce4-8788-4a80-af60-aa43f8ae7233.png)

Before depreciating the stand alone registry, we need to decide whether to carry over any of this text, and it's placement on the Dashboard.

**Comment by mariongalley** [comment]
Note that the Registry also has a burger menu in the nav that links to our website and tools.

Other newer tools such as Insights include these links in the footer.

**Comment by mariongalley** [comment]
@codemacabre Could we make the header and footer the same as our other tools e.g. Insights (with different copy/links) but keeping the narrower header? Happy to raise a separate ticket for that if helpful

**Comment by mariongalley** [comment]
Thanks @codemacabre - We'd like to keep the skinny header for the Quality Dashboard, but add a navigation bar at the top, which will be the same as our other tools including Insights, our website, the current Registry etc

![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/ab846db0-09ed-4f28-b1d6-ee33d3f5a441)

In terms of the footer, it would be great if it were the same form as our other sites like our website, GrantNav and Insights, including the Newsletter sign up 

![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/55254b72-e6bd-4fba-b31f-2150aa194122)

We'll need some copy about the Data Quality Dashboard itself. Can you use this for now please?

> A dashboard showing the data quality of 360Giving data as a whole and for each individual publisher. It provides insights into the key features that make the data useful for analysis to help publishers to identify opportunities for their data to be improved.

**Comment by codemacabre** [comment]
Thanks @mariongalley, all sounds good. Quick question about the copyright year; Insights currently says 2022, GrantNav and Registry / DQD say 2021:

Do you want these to be updated to 2023? Do you want them to be automatically updated to the current year? If so, this may need to be a separate issue but thought I'd mention it as I spotted it.

**Comment by mariongalley** [comment]
Thanks @codemacabre , I checked with my team and usually the copyright year is the year the copy was written, so people update it when they launch a new website or make substantial changes. We're happy for these to only be updated when we make any substantial changes, so it can be done manually. Currently don't think we need to update the DQD copyright.

**Comment by codemacabre** [comment]
@mariongalley Whoops, sorry! I was clearing up a few issues this morning and missed that initial issue. Do you know if we'll be carrying over the text and if so, where its placement should be?

**Comment by mariongalley** [comment]
@codemacabre We checked the analytics and those links are quite well-used, so we do want to carry over the text. In terms of the placement, we haven't really got a home for it currently so will need to think about. Welcome any suggestions you might have also

**Comment by mariongalley** [comment]
@KDuerden I've had another look at this and I think we can get rid of this text:
- "This registry lists 228 organisations that publish data about their grants to the 360Giving Data Standard." can go as it is superseded by the 228 publishers headline stat
- "Looking to explore the grants data by location, sector or recipient? Head to GrantNav." is superseded by the existence of the GrantNav link in both the header and footer (analytics shows that the GrantNav link does get a good amount of click-throughs from the Quality Dashboard)
- In terms of the link to the JSON Feed, we could keep this as a bit of copy at the top of the page, but I'd be inclined to replace it with a link in the nav called "Technical users", and change the link to direct to the top of the technical users page rather than the JSON feed specifically, as in future this will also direct to our API.
- In terms of the link to the support page, I'd replace this with a link in the nav to "Why Publish?" (or how to publish)

This means the navigation would be: GrantNav, Insights, About 360Giving, Why Publish, Technical Users

@codemacabre Please can you implement this in dev?

**Comment by codemacabre** [comment]
@mariongalley This is now on the dev server.

**Comment by mariongalley** [comment]
Thanks @codemacabre - sorry I didn't make it very clear that some of the destination URLs I'm proposing to supersede the old information are slightly different from what we linked to previously
- Please can Why Publish? direct to https://www.threesixtygiving.org/why-publish/ instead of the Services & Support page
- Please can Technical users direct to https://www.threesixtygiving.org/technical-users/ rather than specifically the JSON Feed?

**Comment by codemacabre** [comment]
@mariongalley Updated :)
