### ISSUE TITLE
User story #9 - Changes to file

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#9]
As a data user I want to know when a file is changed so I will know if I can use it.

**Comment by stevieflow** [comment]
What is meant by "changes to a file" here?

It could be:

- that it has changed from being available to not available
- that it has changed in terms of download URL
- that it has changed in terms of schema validation result (pass > fail; fail > pass)
- that existing grant records have changed
- that new grant records have been added
- that grant records have been removed

I don't know if any of these answer the story "so that I can use it".  The only thing that would *stop* you using it would be the first test

**Comment by morchickit** [comment]
We mean changes of getting hold of the file, not changing to the file data itself. Changes to file data will have a different user story.  

So the user story should be - I want to know if the file is available so I can download and use it. By that we mean that we want to see - 

- that it has changed from being available to not available
- that it has changed in terms of download URL
- that it has changed in terms of schema validation result (pass > fail; fail > pass)

**Comment by robredpath** [comment]
@morchickit how important is the former state of the file to this user story? 

If it's "As a data user I want to know if a file is available, valid and where to download it so that I can use it", then that doesn't require us to store any history

If it's "As a data user, I want to know if a file has previously been available, valid and available at a certain location so that.....?", then we need to retain and provide some level of historical information about former availability, validity and download URLs.

**Comment by stevieflow** [comment]
NB: we also discussed that there is a ``modified`` field in both the record and metadata.  We discussed using that in the registry (probably the metadata) to indicate last changed to users

However - I think that is a separate task / user story @robredpath  ?

In terms of recording when the file availability has changed, would this require an additional service to log / check / compare @robredpath ?

**Comment by robredpath** [comment]
> However - I think that is a separate task / user story @robredpath ?

@stevieflow yeah, I think that "As someone who wants to use the data, I want know when the file was last updated so that I can make a decision about whether the data is suitable for me" is separate from here. 

What I'm not clear on is *why* someone would want to know what the previous state of a file was - I can only see why someone would want to know the current state of the file. @morchickit - can you expand on that? Why would a registry user want to know if a file used to have a different URL, for example?

**Comment by morchickit** [comment]
I don't understand what you mean, @robredpath . If you mean validation, then for that I just mean to see when it's valid and when it's not. If the data is available I want to know if there is a URL or the URL is not available. I might want to get a notification if a file was not valid but now it is valid.

**Comment by stevieflow** [comment]
I think we discussed / agreed that date we would use , for any file, would be:

- The latest dateModified dateTime

In terms of this:
 - We know that ``dateModified`` is at the record level, and populated by publishers
- We know that ``dateModified`` can differ across records
- We haven't lots (or any?) of evidence that active publishers change their ``dateModified`` across records 
- We know some publishers update their ``dateModified`` field when they update the file (probably for all records)

If we use ``dateModified`` from the data, and display it on the Registry then:

a) this puts the data in use
b) publishers can be guided as how to act upon it

I think we need to agree this, as this then has an impact on @Bjwebb changing the metadata output, for example

--> @morchickit @robredpath 

cc/ @KDuerden

**Comment by robredpath** [comment]
@stevieflow what you describe is my understanding of what we should do.
