### ISSUE TITLE
Add number of Funders

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#95]
Add number of funders somewhere alongside or near number of publishers to disambiguate between the two

**Comment by michaelwood** [comment]
Mock up -

![Screenshot from 2022-04-27 11-23-10](https://user-images.githubusercontent.com/493697/165497780-176c3555-7fae-422c-8989-aacb28976897.png)

Is this the desired position? The [design system doesn't currently incorporate a 5 column grid](https://github.com/ThreeSixtyGiving/360-ds/blob/master/src/components/04-modules/grid/grid.scss#L19), but we could try developing one.

**Comment by michaelwood** [comment]
Add funder count to summary stats now deployed.

**Comment by mariongalley** [comment]
> Ah I thought that was expected, maybe my screenshot in the pr review didn't show it well enough.

Hmmm, maybe this is my foggy brain but I'm not sure I remember seeing a screenshot in a PR Review.

@KDuerden What do you think? Is the variable width OK or should we look into one of the 3 options above?

**Comment by robredpath** [comment]
> Reduce the size of the values/text (e.g. use "327.5k" instead of the full number)

If we drop the decimals across the board, then we're getting towards a more consistent width: 3/3/4/4/6 chars for 204/226/327k/729k/£174bn, instead of 3/3/7/7/9. 

That might be an easy way (depending on how hard generating those values is) of making it less obvious? 

And/or - rearranging the boxes might make it less jarring than having them in order. Maybe 6/4/3/4/3 ?

**Comment by michaelwood** [comment]
> > Ah I thought that was expected, maybe my screenshot in the pr review didn't show it well enough.
> 
> Hmmm, maybe this is my foggy brain but I'm not sure I remember seeing a screenshot in a PR Review.

The screenshot in pr https://github.com/ThreeSixtyGiving/registry/pull/105#issue-1245338392 , but yes the responsive design doesn't show the issue very well because when I screenshot the page I made the web browser window smaller which triggers a responsive design rules that reduces the amount of padding around the text in the cards. (This is especially easy to see if you look at the distance between the edge and the £ sign when changing the browser window width).

**Comment by robredpath** [comment]
> and the £ sign

(also, the £ is a massive glyph, we could make that a few points smaller and save a few pixels!)

**Comment by mariongalley** [comment]
Agreed with Katherine that we don't want to introduce rounding and the boxes being different sizes is fine.
